### ISSUE TITLE
Broken Pipe

### ISSUE THREAD

**Issue by varunmayya** [facebookresearch/audio2photoreal#10]
This looks like an FFMPEG issue, but I have the latest FFMPEG, so not sure what's going on

Traceback (most recent call last):
  File "/root/anaconda3/envs/a2p_env/lib/python3.9/site-packages/mediapy/__init__.py", line 1749, in write_video
    writer.add_image(image)
  File "/root/anaconda3/envs/a2p_env/lib/python3.9/site-packages/mediapy/__init__.py", line 1653, in add_image
    if stdin.write(data) != len(data):
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/a2p_env/lib/python3.9/site-packages/gradio/queueing.py", line 489, in call_prediction
    output = await route_utils.call_process_api(
  File "/root/anaconda3/envs/a2p_env/lib/python3.9/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/root/anaconda3/envs/a2p_env/lib/python3.9/site-packages/gradio/blocks.py", line 1561, in process_api
    result = await self.call_function(
  File "/root/anaconda3/envs/a2p_env/lib/python3.9/site-packages/gradio/blocks.py", line 1179, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/root/anaconda3/envs/a2p_env/lib/python3.9/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/root/anaconda3/envs/a2p_env/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "/root/anaconda3/envs/a2p_env/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/root/anaconda3/envs/a2p_env/lib/python3.9/site-packages/gradio/utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
  File "/root/audio2photoreal/demo/demo.py", line 226, in audio_to_avatar
    gradio_model.body_renderer.render_full_video(
  File "/root/audio2photoreal/visualize/render_codes.py", line 153, in render_full_video
    self._write_video_stream(
  File "/root/audio2photoreal/visualize/render_codes.py", line 95, in _write_video_stream
    mediapy.write_video(save_name, out, fps=30)
  File "/root/anaconda3/envs/a2p_env/lib/python3.9/site-packages/mediapy/__init__.py", line 1749, in write_video
    writer.add_image(image)
  File "/root/anaconda3/envs/a2p_env/lib/python3.9/site-packages/mediapy/__init__.py", line 1614, in __exit__
    self.close()
  File "/root/anaconda3/envs/a2p_env/lib/python3.9/site-packages/mediapy/__init__.py", line 1671, in close
    raise RuntimeError(f"Error writing '{self.path}': {s}")
RuntimeError: Error writing '/tmp/pred_tmp_sample0.mp4': Unrecognized option 'qp'.
Error splitting the argument list: Option not found

**Comment by choyongki** [comment]
did you solved it?
