### ISSUE TITLE
RuntimeError: Not compiled with GPU support ( but i have GPU )

### ISSUE THREAD

**Issue by ehsanwwe** [facebookresearch/audio2photoreal#70]
i has been confuse
i have CUDA
pytorch detect my cuda but when i want to run demo
torch version = 2.0.
torch cuda version = cu117
cudatoolkit = 12.6 ( there is no cu117 version in NVIDIA version)
i test this code in WSL
Windows 11
and UBUNTU 24

also i test it in 
the same PC with Cuda toolkit 12.4 and cuda 12.4 ( nvidia RTX 4080 )

i got this error at end of my log box
-------------------------------------
$ python -m demo.demo
running on... cuda:0
 adding lip conditioning ./assets/iter-0200000.pt
Loading checkpoints from [checkpoints/diffusion/c1_face/model000155000.pt]...
running on... cuda:0
 using keyframes: torch.Size([1, 20, 256])
loading checkpoint from checkpoints/vq/c1_pose/net_iter300000.pth
 loading TRANSFORMER checkpoint from checkpoints/guide/c1_pose/checkpoints/iter-0100000.pt
Loading checkpoints from [checkpoints/diffusion/c1_pose/model000340000.pt]...
Traceback (most recent call last):
  File "/home/ehsan/anaconda3/envs/a2p_env/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ehsan/anaconda3/envs/a2p_env/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ehsan/PycharmProject/audio2photoreal-1.0/demo/demo.py", line 227, in <module>
    gradio_model = GradioModel(
  File "/home/ehsan/PycharmProject/audio2photoreal-1.0/demo/demo.py", line 33, in __init__
    self.body_renderer = BodyRenderer(
  File "/home/ehsan/PycharmProject/audio2photoreal-1.0/visualize/render_codes.py", line 62, in __init__
    self.model = load_from_config(config.model, assets=static_assets).to(
  File "/home/ehsan/PycharmProject/audio2photoreal-1.0/visualize/ca_body/utils/train.py", line 67, in load_from_config
    instance = object_class(**config, **kwargs)
  File "/home/ehsan/PycharmProject/audio2photoreal-1.0/visualize/ca_body/models/mesh_vae_drivable.py", line 86, in __init__
    self.geo_fn = GeometryModule(
  File "/home/ehsan/PycharmProject/audio2photoreal-1.0/visualize/ca_body/utils/geom.py", line 216, in __init__
    index_image = make_uv_vert_index(
  File "/home/ehsan/PycharmProject/audio2photoreal-1.0/visualize/ca_body/utils/geom.py", line 74, in make_uv_vert_index
    face_index_map = make_uv_face_index(vt, vti, uv_shape, flip_uv).to(vi.device)
  File "/home/ehsan/PycharmProject/audio2photoreal-1.0/visualize/ca_body/utils/geom.py", line 56, in make_uv_face_index
    face_index, _, _, _ = rasterize_meshes(
  File "/home/ehsan/anaconda3/envs/a2p_env/lib/python3.9/site-packages/pytorch3d/renderer/mesh/rasterize_meshes.py", line 225, in rasterize_meshes
    pix_to_face, zbuf, barycentric_coords, dists = _RasterizeFaceVerts.apply(
  File "/home/ehsan/anaconda3/envs/a2p_env/lib/python3.9/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/ehsan/anaconda3/envs/a2p_env/lib/python3.9/site-packages/pytorch3d/renderer/mesh/rasterize_meshes.py", line 298, in forward
    pix_to_face, zbuf, barycentric_coords, dists = _C
.rasterize_meshes(
RuntimeError: Not compiled with GPU support

**Comment by evonneng** [comment]
Hi! thanks for your interest in our project. It seems like while you have gpus on your device, perhaps pytorch or one of your libraries has not registered this. could you check to see if you run `torch.cuda.is_available()` it returns true?

**Comment by ehsanwwe** [comment]
I tested cuda by that code always return true , i think cause of this error is depended to another facebookreaserch library that used in this project
Do you have an idea , i run and install it from beggining multiple times in multiple os and ..

**Comment by evonneng** [comment]
Hmm my only idea is that maybe the pytorch version is not compatible with the cuda version you have? In the readme we specify a specific cuda and pytorch version we support. Since it seems like a pytorch3d issue, could you try reinstalling it as per this similar issue: https://github.com/facebookresearch/pytorch3d/issues/1565 to see what happens?

**Comment by evonneng** [comment]
Closing due to inactivity, please feel free to reopen if you have further questions
