### ISSUE TITLE
IndexError: cannot do a non-empty take from an empty axes.

### ISSUE THREAD

**Issue by XuJianzhi** [facebookresearch/audio2photoreal#72]
i run "python -m sample.generate --model_path checkpoints/diffusion/c1_face/model000155000.pt --num_samples 10 --num_repetitions 5 --timestep_respacing ddim500 --guidance_param 10.0"

bug: "(a2p_env) root@job-3932-1724393121-nz25j:/data/try/cv/audio2photoreal-main# python -m sample.generate --model_path checkpoints/diffusion/c1_face/model000155000.pt --num_samples 10 --num_repetitions 5 --timestep_respacing ddim500 --guidance_param 10.0
checkpoints/diffusion/c1_face/args.json
Warning: was not able to load [split], using default value [None] instead.
Loading dataset...
 [dataset.py] training face only model
 ['[dataset.py] sequences of 600']
Traceback (most recent call last):
  File "/opt/conda/envs/a2p_env/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/a2p_env/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/try/cv/audio2photoreal-main/sample/generate.py", line 316, in <module>
    main()
  File "/data/try/cv/audio2photoreal-main/sample/generate.py", line 277, in main
    test_data = _setup_dataset(args)
  File "/data/try/cv/audio2photoreal-main/sample/generate.py", line 243, in _setup_dataset
    test_data = get_dataset_loader(
  File "/data/try/cv/audio2photoreal-main/data_loaders/get_data.py", line 28, in get_dataset_loader
    dataset = Social(
  File "/data/try/cv/audio2photoreal-main/data_loaders/data.py", line 61, in __init__
    self._pick_sequences(data_dict, test_idx)
  File "/data/try/cv/audio2photoreal-main/data_loaders/data.py", line 94, in _pick_sequences
    self.data = np.take(data_dict["data"], idx, axis=0)
  File "<__array_function__ internals>", line 180, in take
  File "/opt/conda/envs/a2p_env/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 190, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)
  File "/opt/conda/envs/a2p_env/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/opt/conda/envs/a2p_env/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
IndexError: cannot do a non-empty take from an empty axes.
"

**Comment by XuJianzhi** [comment]
i found: 
      data_dict: {'data': [], 'face': [], 'audio': [], 'lengths': [], 'missing': []}
because:
      "python -m sample.generate --model_path checkpoints/diffusion/c1_face/model000155000.pt --num_samples 10 --num_repetitions 5 --timestep_respacing ddim500 --guidance_param 10.0" 
        have no "args.data_root"
how to do?

**Comment by evonneng** [comment]
Closing due to inactivity, please reopen if you have any other questions
